# CMAKE generated file: DO NOT EDIT!
# Generated by "Unix Makefiles" Generator, CMake Version 3.27

# Default target executed when no arguments are given to make.
default_target: all
.PHONY : default_target

# Allow only one "make -f Makefile2" at a time, but pass parallelism.
.NOTPARALLEL:

#=============================================================================
# Special targets provided by cmake.

# Disable implicit rules so canonical targets will work.
.SUFFIXES:

# Disable VCS-based implicit rules.
% : %,v

# Disable VCS-based implicit rules.
% : RCS/%

# Disable VCS-based implicit rules.
% : RCS/%,v

# Disable VCS-based implicit rules.
% : SCCS/s.%

# Disable VCS-based implicit rules.
% : s.%

.SUFFIXES: .hpux_make_needs_suffix_list

# Command-line flag to silence nested $(MAKE).
$(VERBOSE)MAKESILENT = -s

#Suppress display of executed commands.
$(VERBOSE).SILENT:

# A target that is always out of date.
cmake_force:
.PHONY : cmake_force

#=============================================================================
# Set environment variables for the build.

# The shell in which to execute make rules.
SHELL = /bin/sh

# The CMake executable.
CMAKE_COMMAND = /opt/homebrew/Cellar/cmake/3.27.7/bin/cmake

# The command to remove a file.
RM = /opt/homebrew/Cellar/cmake/3.27.7/bin/cmake -E rm -f

# Escaping for special characters.
EQUALS = =

# The top-level source directory on which CMake was run.
CMAKE_SOURCE_DIR = /Users/harshavardhan/Documents/DIP/LipFlip/src

# The top-level build directory on which CMake was run.
CMAKE_BINARY_DIR = /Users/harshavardhan/Documents/DIP/LipFlip/src

#=============================================================================
# Targets provided globally by CMake.

# Special rule for the target edit_cache
edit_cache:
	@$(CMAKE_COMMAND) -E cmake_echo_color "--switch=$(COLOR)" --cyan "Running CMake cache editor..."
	/opt/homebrew/Cellar/cmake/3.27.7/bin/ccmake -S$(CMAKE_SOURCE_DIR) -B$(CMAKE_BINARY_DIR)
.PHONY : edit_cache

# Special rule for the target edit_cache
edit_cache/fast: edit_cache
.PHONY : edit_cache/fast

# Special rule for the target rebuild_cache
rebuild_cache:
	@$(CMAKE_COMMAND) -E cmake_echo_color "--switch=$(COLOR)" --cyan "Running CMake to regenerate build system..."
	/opt/homebrew/Cellar/cmake/3.27.7/bin/cmake --regenerate-during-build -S$(CMAKE_SOURCE_DIR) -B$(CMAKE_BINARY_DIR)
.PHONY : rebuild_cache

# Special rule for the target rebuild_cache
rebuild_cache/fast: rebuild_cache
.PHONY : rebuild_cache/fast

# The main all target
all: cmake_check_build_system
	$(CMAKE_COMMAND) -E cmake_progress_start /Users/harshavardhan/Documents/DIP/LipFlip/src/CMakeFiles /Users/harshavardhan/Documents/DIP/LipFlip/src//CMakeFiles/progress.marks
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 all
	$(CMAKE_COMMAND) -E cmake_progress_start /Users/harshavardhan/Documents/DIP/LipFlip/src/CMakeFiles 0
.PHONY : all

# The main clean target
clean:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 clean
.PHONY : clean

# The main clean target
clean/fast: clean
.PHONY : clean/fast

# Prepare targets for installation.
preinstall: all
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 preinstall
.PHONY : preinstall

# Prepare targets for installation.
preinstall/fast:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 preinstall
.PHONY : preinstall/fast

# clear depends
depend:
	$(CMAKE_COMMAND) -S$(CMAKE_SOURCE_DIR) -B$(CMAKE_BINARY_DIR) --check-build-system CMakeFiles/Makefile.cmake 1
.PHONY : depend

#=============================================================================
# Target rules for targets named lip_flip

# Build rule for target.
lip_flip: cmake_check_build_system
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 lip_flip
.PHONY : lip_flip

# fast build rule for target.
lip_flip/fast:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/lip_flip.dir/build.make CMakeFiles/lip_flip.dir/build
.PHONY : lip_flip/fast

DetectionTools.o: DetectionTools.cpp.o
.PHONY : DetectionTools.o

# target to build an object file
DetectionTools.cpp.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/lip_flip.dir/build.make CMakeFiles/lip_flip.dir/DetectionTools.cpp.o
.PHONY : DetectionTools.cpp.o

DetectionTools.i: DetectionTools.cpp.i
.PHONY : DetectionTools.i

# target to preprocess a source file
DetectionTools.cpp.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/lip_flip.dir/build.make CMakeFiles/lip_flip.dir/DetectionTools.cpp.i
.PHONY : DetectionTools.cpp.i

DetectionTools.s: DetectionTools.cpp.s
.PHONY : DetectionTools.s

# target to generate assembly for a file
DetectionTools.cpp.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/lip_flip.dir/build.make CMakeFiles/lip_flip.dir/DetectionTools.cpp.s
.PHONY : DetectionTools.cpp.s

ImageTools.o: ImageTools.cpp.o
.PHONY : ImageTools.o

# target to build an object file
ImageTools.cpp.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/lip_flip.dir/build.make CMakeFiles/lip_flip.dir/ImageTools.cpp.o
.PHONY : ImageTools.cpp.o

ImageTools.i: ImageTools.cpp.i
.PHONY : ImageTools.i

# target to preprocess a source file
ImageTools.cpp.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/lip_flip.dir/build.make CMakeFiles/lip_flip.dir/ImageTools.cpp.i
.PHONY : ImageTools.cpp.i

ImageTools.s: ImageTools.cpp.s
.PHONY : ImageTools.s

# target to generate assembly for a file
ImageTools.cpp.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/lip_flip.dir/build.make CMakeFiles/lip_flip.dir/ImageTools.cpp.s
.PHONY : ImageTools.cpp.s

LaplacianBlending.o: LaplacianBlending.cpp.o
.PHONY : LaplacianBlending.o

# target to build an object file
LaplacianBlending.cpp.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/lip_flip.dir/build.make CMakeFiles/lip_flip.dir/LaplacianBlending.cpp.o
.PHONY : LaplacianBlending.cpp.o

LaplacianBlending.i: LaplacianBlending.cpp.i
.PHONY : LaplacianBlending.i

# target to preprocess a source file
LaplacianBlending.cpp.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/lip_flip.dir/build.make CMakeFiles/lip_flip.dir/LaplacianBlending.cpp.i
.PHONY : LaplacianBlending.cpp.i

LaplacianBlending.s: LaplacianBlending.cpp.s
.PHONY : LaplacianBlending.s

# target to generate assembly for a file
LaplacianBlending.cpp.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/lip_flip.dir/build.make CMakeFiles/lip_flip.dir/LaplacianBlending.cpp.s
.PHONY : LaplacianBlending.cpp.s

main.o: main.cpp.o
.PHONY : main.o

# target to build an object file
main.cpp.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/lip_flip.dir/build.make CMakeFiles/lip_flip.dir/main.cpp.o
.PHONY : main.cpp.o

main.i: main.cpp.i
.PHONY : main.i

# target to preprocess a source file
main.cpp.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/lip_flip.dir/build.make CMakeFiles/lip_flip.dir/main.cpp.i
.PHONY : main.cpp.i

main.s: main.cpp.s
.PHONY : main.s

# target to generate assembly for a file
main.cpp.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/lip_flip.dir/build.make CMakeFiles/lip_flip.dir/main.cpp.s
.PHONY : main.cpp.s

# Help Target
help:
	@echo "The following are some of the valid targets for this Makefile:"
	@echo "... all (the default if no target is provided)"
	@echo "... clean"
	@echo "... depend"
	@echo "... edit_cache"
	@echo "... rebuild_cache"
	@echo "... lip_flip"
	@echo "... DetectionTools.o"
	@echo "... DetectionTools.i"
	@echo "... DetectionTools.s"
	@echo "... ImageTools.o"
	@echo "... ImageTools.i"
	@echo "... ImageTools.s"
	@echo "... LaplacianBlending.o"
	@echo "... LaplacianBlending.i"
	@echo "... LaplacianBlending.s"
	@echo "... main.o"
	@echo "... main.i"
	@echo "... main.s"
.PHONY : help



#=============================================================================
# Special targets to cleanup operation of make.

# Special rule to run CMake to check the build system integrity.
# No rule that depends on this can have commands that come from listfiles
# because they might be regenerated.
cmake_check_build_system:
	$(CMAKE_COMMAND) -S$(CMAKE_SOURCE_DIR) -B$(CMAKE_BINARY_DIR) --check-build-system CMakeFiles/Makefile.cmake 0
.PHONY : cmake_check_build_system

